<a href="https://colab.research.google.com/github/rharvey242/Linear_Algebra_Coding_projects/blob/main/Gram_Schmidt_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [44]:
#run 1
r1=np.matrix([[3],[0],[3],[0]])
r1

matrix([[3],
        [0],
        [3],
        [0]])

In [31]:
3*r1

matrix([[9],
        [0],
        [9],
        [0]])

In [32]:
r1=np.array([3,0,3,0])
r1

array([3, 0, 3, 0])

In [33]:
r1.dot(r1)

18

In [34]:
#magnitute of vector 1
np.sqrt(r1.dot(r1))

4.242640687119285

#Gram Schmidt orthonormalization Process

we'll use the gram schmidt proccess to find orthonoraml vectors in $R^4$

##Our random vectors: 




In [45]:
r1=np.array([3,0,3,0])
r2=np.array([3,2,3,3])
r3=np.array([-7,-4,-5,-6])
r4=np.array([-7,-3,-11,2])


#process r1
#choose the vector and subrtract off the nice orthganal pieces
t1=r1
t1
m =np.sqrt(t1.dot(t1))
u1=(1/m)*t1
u1

array([0.70710678, 0.        , 0.70710678, 0.        ])

In [48]:
#process r2
t2=r2-(u1.dot(r2))*u1
t2
m = np.sqrt(  t2.dot(t2) )
m
# create normal
u2=(1/m)*t2
u2

array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

In [49]:

#process r3
t3=r3-(u1.dot(r3))*u1-(u2.dot(r3))*u2
t3
m = np.sqrt(  t3.dot(t3) )
m
# create normal
u3=(1/m)*t3
u3

array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])

In [50]:
#process r4
t4=r4-(u1.dot(r4))*u1-(u2.dot(r4))*u2-(u3.dot(r4))*u3
t3
m = np.sqrt(  t3.dot(t3) )
m
# create normal
u3=(1/m)*t3
u3

array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])